commonLabel = {
    register: "ثبت نام",
    login: "ورود",
    username: "نام کاربری",
    password: "رمز عبور",
    cancel: "لغو",
    userLogin: "ورود کاربران",
    email: "ایمیل",
    userRegistration: "ثبت نام کاربران",
    repoConfigs : "تنظیمات رپو",
    projectManagement : "مدیریت پروژه",
    repo :"رپو",
    clone:"چک اوت",
    issues:"مشکلات",
    userConfigs:"تنظیمات کاربری",
    signOut:"ساین اوت",
    settings:"تنظیمات",
    userInfo:"اطلاعات کاربری",
    notification:"پیام ها",
    devistan:"دویستان",
    messageBoxTest : "این یک تست فقط برای نشان دادن پیغام هاست جدی نگیرید",
    messageBoxTestHeader :"پیغام"
};
